<?php

declare(strict_types=1);

namespace App\Filament\Pages;

use BackedEnum;
use Filament\Actions\Action;
use Filament\Notifications\Notification;
use Filament\Pages\Page;
use Filament\Support\Icons\Heroicon;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Artisan;

/**
 * The sitemap is generated by the scheduler (app:GenerateSitemap, nightly);
 * this page shows the last generation and lets an operator regenerate it now.
 * The legacy admin regenerated it on every page view.
 */
final class Sitemap extends Page
{
    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedMap;

    protected static ?int $navigationSort = 50;

    protected string $view = 'filament.pages.sitemap';

    public static function getNavigationGroup(): string
    {
        return __('admin.nav.content');
    }

    public static function getNavigationLabel(): string
    {
        return __('admin.content.sitemap');
    }

    public function getTitle(): string
    {
        return __('admin.content.sitemap');
    }

    public static function canAccess(): bool
    {
        return auth()->user()?->can('content.manage') ?? false;
    }

    public function getGeneratedAt(): ?Carbon
    {
        $file = public_path('sitemap.xml');

        return is_file($file) ? Carbon::createFromTimestamp((int) filemtime($file)) : null;
    }

    public function getUrlCount(): int
    {
        $file = public_path('sitemap.xml');

        return is_file($file) ? substr_count((string) file_get_contents($file), '<loc>') : 0;
    }

    protected function getHeaderActions(): array
    {
        return [
            Action::make('regenerate')->label(__('admin.content.sitemap_regenerate'))->icon(Heroicon::OutlinedArrowPath)
                ->action(function (): void {
                    Artisan::call('app:GenerateSitemap');
                    Notification::make()->title(__('admin.content.sitemap_done'))->success()->send();
                }),
            Action::make('open')->label(__('admin.content.sitemap_open'))->icon(Heroicon::OutlinedArrowTopRightOnSquare)->color('gray')
                ->url(url('/sitemap.xml'), shouldOpenInNewTab: true)
                ->visible(fn (): bool => $this->getGeneratedAt() !== null),
        ];
    }
}
